apiVersion: v1
data:
  DB_HOST: {{ .Values.configmap.data.DB_HOST }}
  DB_NAME: {{ .Values.configmap.data.DB_NAME }}
  DB_PASS: {{ .Values.configmap.data.DB_PASS }}
  DB_PORT: "{{ .Values.configmap.data.DB_PORT }}"
  DB_USER: {{ .Values.configmap.data.DB_USER }}
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
