apiVersion: v1
kind: Service
metadata:
  labels:
    app: song-choices
  name: song-choices
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: song-choices
  type: ClusterIP
