appName: singers

configmap: 
  name: singers-config
  data: 
    DB_HOST: postgres-postgresql
    DB_NAME: postgres
    DB_PASS: postgres
    DB_PORT: 5432
    DB_USER: postgres
    

image:
  name: lukewyman/singers
  tag: v1.0.0

replicas: 1

resources: 
  requests: 
    cpu: 500m
    memory: 512Mi
  limits: 
    cpu: 1000m
    memory: 1Gi