apiVersion: v1
data:
  AWS_REGION: {{ .Values.configmap.data.AWS_REGION }}
  QUEUES_TABLE_NAME: {{ .Values.configmap.data.QUEUES_TABLE_NAME }}
  SINGERS_TABLE_NAME: {{ .Values.configmap.data.SINGERS_TABLE_NAME }}
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
