apiVersion: v1
kind: Service
metadata:
  labels:
    app: song-library
  name: song-library
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: song-library
  type: ClusterIP
  