appName: song-choices

configmap: 
  name: song-choices-config
  data: 
    AWS_REGION: us-west-2
    SONG_CHOICES_TABLE_NAME: karaoke-app-local-dev-song-choices
    SONG_LIBRARY_SERVICE: song-library

image:
  name: lukewyman/song-choices
  tag: v1.0.0

replicas: 1

resources: 
  requests: 
    cpu: 500m
    memory: 512Mi
  limits: 
    cpu: 1000m
    memory: 1Gi