apiVersion: v1
kind: Service
metadata:
  labels:
    app: singers
  name: singers
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: singers
  type: ClusterIP
