appName: song-library

configmap: 
  name: song-library-config
  data: 
    MONGO_HOSTNAME: mongo-mongodb
    MONGO_PASSWORD: p@ssw0RD123
    MONGO_PORT: 27017
    MONGO_USERNAME: admin
    

image:
  name: lukewyman/song-library
  tag: v1.0.0

replicas: 1

resources: 
  requests: 
    cpu: 500m
    memory: 512Mi
  limits: 
    cpu: 1000m
    memory: 1Gi